[."topic"]
[#scalability]
= EKS Scalability best practices
:info_titleabbrev: Scalability
:imagesdir: images/scalability/

This guide provides advice for scaling EKS clusters. The goal of scaling an EKS cluster is to maximize the amount of work a single cluster can perform. Using a single, large EKS cluster can reduce operational load compared to using multiple clusters, but it has trade-offs for things like multi-region deployments, tenant isolation, and cluster upgrades. In this document we will focus on how to achieve maximum scalability with a single cluster.

== How to use this guide

This guide is meant for developers and administrators responsible for creating and managing EKS clusters in AWS. It focuses on some generic Kubernetes scaling practices, but it does not have specifics for self-managed Kubernetes clusters or clusters that run outside of an AWS region with https://anywhere.eks.amazonaws.com/[EKS Anywhere].

Each topic has a brief overview, followed by recommendations and best practices for operating EKS clusters at scale. Topics do not need to be read in a particular order and recommendations should not be applied without testing and verifying they work in your clusters.

== Understanding scaling dimensions

Scalability is different from performance and https://aws.github.io/aws-eks-best-practices/reliability/docs/[reliability], and all three should be considered when planning your cluster and workload needs. As clusters scale, they need to be monitored, but this guide will not cover monitoring best practices. EKS can scale to large sizes, but you will need to plan how you are going to scale a cluster beyond 300 nodes or 5000 pods. These are not absolute numbers, but they come from collaborating this guide with multiple users, engineers, and support professionals.

Scaling in Kubernetes is multi-dimensional and there are no specific settings or recommendations that work in every situation. The main areas areas where we can provide guidance for scaling include:

// * xref:control-plane[Kubernetes Control Plane]
// * xref:data-plane[Kubernetes Data Plane]
// * xref:cluster-services[Cluster Services]
// * xref:workloads[Workloads]

*Kubernetes Control Plane* in an EKS cluster includes all of the services AWS runs and scales for you automatically (e.g. Kubernetes API server). Scaling the Control Plane is AWS's responsibility, but using the Control Plane responsibly is your responsibility.

*Kubernetes Data Plane* scaling deals with AWS resources that are required for your cluster and workloads, but they are outside of the EKS Control Plane. Resources including EC2 instances, kubelet, and storage all need to be scaled as your cluster scales.

*Cluster services* are Kubernetes controllers and applications that run inside the cluster and provide functionality for your cluster and workloads. These can be https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html[EKS Add-ons] and also other services or Helm charts you install for compliance and integrations. These services are often depended on by workloads and as your workloads scale your cluster services will need to scale with them.

*Workloads* are the reason you have a cluster and should scale horizontally with the cluster. There are integrations and settings that workloads have in Kubernetes that can help the cluster scale. There are also architectural considerations with Kubernetes abstractions such as namespaces and services.

== Extra large scaling

If you are scaling a single cluster beyond 1000 nodes or 50,000 pods we would love to talk to you. We recommend reaching out to your support team or technical account manager to get in touch with specialists who can help you plan and scale beyond the information provided in this guide.

include::control-plane.adoc[leveloffset=+1]

include::data-plane.adoc[leveloffset=+1]

include::cluster-services.adoc[leveloffset=+1]

include::workloads.adoc[leveloffset=+1]

include::scaling_theory.adoc[leveloffset=+1]

include::kcp_monitoring.adoc[leveloffset=+1]

include::node_efficiency.adoc[leveloffset=+1]

include::kubernetes_slos.adoc[leveloffset=+1]

include::quotas.adoc[leveloffset=+1]

