//!!NODE_ROOT <chapter>
[."topic"]
[[introduction,introduction.title]]
= Amazon EKS Best Practices Guide
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: Amazon EKS Best Practices Guide
:info_titleabbrev: Introduction
:info_abstract: Learn best practices for operating EKS clusters.

[abstract]
--
Learn best practices for operating EKS clusters.
--

Welcome to the EKS Best Practices Guides. The primary goal of this
project is to offer a set of best practices for day 2 operations for
Amazon EKS. We elected to publish this guidance to GitHub so we could
iterate quickly, provide timely and effective recommendations for
variety of concerns, and easily incorporate suggestions from the broader
community.

We currently have published guides for the following topics:

* xref:security[Best Practices for Security]
* xref:reliability[Best Practices for Reliability]
* xref:karpenter[Best Practices for Cluster Autoscaling: Karpenter]
* xref:cas[Best Practices for Cluster Autoscaling: cluster-autoscaler]
* xref:automode[Best Practices for Cluster Autoscaling: EKS Auto Mode]
* xref:networking[Best Practices for Networking]
* xref:scalability[Best Practices for Scalability]
* xref:cluster-upgrades[Best Practices for Cluster Upgrades]
* xref:cost-opt[Best Practices for Cost Optimization]
* xref:windows[Best Practices for Running Windows Containers]
* xref:hybrid[Best Practices for Hybrid Deployments]

We also open sourced a Python based CLI (Command Line Interface) called
https://github.com/aws-samples/hardeneks[hardeneks] to check some of the
recommendations from this guide.

In the future we will be publishing best practices guidance for
performance, cost optimization, and operational excellence.

== Related guides

In addition to the
https://docs.aws.amazon.com/eks/latest/userguide/what-is-eks.html[EKS
User Guide], AWS has published several other guides that may help you
with your implementation of EKS.

* https://aws.github.io/aws-emr-containers-best-practices/[EMR
Containers Best Practices Guides]
* https://awslabs.github.io/data-on-eks/[Data on EKS]
* https://aws-observability.github.io/observability-best-practices/[AWS
Observability Best Practices]
* https://aws-ia.github.io/terraform-aws-eks-blueprints/[Amazon EKS
Blueprints for Terraform]
* https://aws-quickstart.github.io/cdk-eks-blueprints/[Amazon EKS
Blueprints Quick Start]

== Contributing

We encourage you to contribute to these guides. If you have implemented
a practice that has proven to be effective, please share it with us by
opening an issue or a pull request. Similarly, if you discover an error
or flaw in the guidance we've already published, please submit a PR to
correct it. The guidelines for submitting PRs can be found in our
https://github.com/aws/aws-eks-best-practices/blob/master/CONTRIBUTING.md[Contributing
Guidelines].


