apiVersion: v1
kind: Service
metadata:
  name: hijack-dns
  namespace: opa-test
spec:
  selector:
    app: hijack-dns-server
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 9053
  externalIPs:
    - 1.1.1.1
    - 2.2.2.2
    - 3.3.3.3
    - 4.4.4.4