//!!NODE_ROOT <chapter>
[[aiml,aiml.title]]
= AI/ML on EKS - Introduction
:info_doctype: chapter
:info_title: Best Practices for Running AI/ML Workloads
:info_abstract: Best Practices for running AI/ML workloads on EKS
:info_titleabbrev: AI/ML 
:imagesdir: images/
:authors: ["Leah Tucker"]
:date: 2025-05-30

TIP: Visit https://aws-experience.com/emea/smb/events/series/get-hands-on-with-amazon-eks?trk=4a9b4147-2490-4c63-bc9f-f8a84b122c8c&sc_channel=elthis[Get Hands on with EKS] to learn about upcoming Amazon EKS AI/ML events and workshops.

Implementing best practices when running AI/ML workloads on EKS can ensure that those workloads are performant, cost-effective, resilient, and properly resourced.
Best practices are divided into the following general sections: Compute, Networking, Storage, Observability, and Performance.

== Feedback

This guide is being released on GitHub so as to collect direct feedback and suggestions from the broader EKS/Kubernetes community. If you have a best practice that you feel we ought to include in the guide, please file an issue or submit a PR in the GitHub repository. Our intention is to update the guide periodically as new features are added to the service or when a new best practice evolves.

include::aiml_compute.adoc[leveloffset=+1]

include::aiml_networking.adoc[leveloffset=+1]

include::aiml_security.adoc[leveloffset=+1]

include::aiml_storage.adoc[leveloffset=+1]

include::aiml_observability.adoc[leveloffset=+1]

include::aiml_performance.adoc[leveloffset=+1]
