//!!NODE_ROOT <section>
:https---docs-aws-amazon-com-awscloudtrail-latest-userguide-getting-notifications-top-level-html: https://docs.aws.amazon.com/awscloudtrail/latest/userguide/getting_notifications_top_level.html
:https---docs-aws-amazon-com-awscloudtrail-latest-userguide-cloudtrail-aws-service-specific-topics-html-cloudtrail-aws-service-specific-topics-integrations: https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-aws-service-specific-topics.html#cloudtrail-aws-service-specific-topics-integrations

[."topic"]
[[logging-using-cloudtrail,logging-using-cloudtrail.title]]
= Logging Amazon EKS API calls using AWS CloudTrail
:info_doctype: section
:info_title: Logging Amazon EKS API calls using AWS CloudTrail
:info_titleabbrev: CloudTrail logs
:info_abstract: Learn about logging Amazon EKS with AWS CloudTrail.

[abstract]
--
Learn about logging Amazon EKS with AWS CloudTrail.
--

Amazon EKS is integrated with AWS CloudTrail, a service that provides a record of actions taken by a user, role, or an AWS service in Amazon EKS. CloudTrail captures all API calls for Amazon EKS as events. The calls captured include calls from the Amazon EKS console and code calls to the Amazon EKS API operations. If you create a trail, you can enable continuous delivery of CloudTrail events to an Amazon S3 bucket, including events for Amazon EKS. If you don't configure a trail, you can still view the most recent events in the CloudTrail console in  **Event history**. Using the information collected by CloudTrail, you can determine the request that was made to Amazon EKS, the IP address from which the request was made, who made the request, when it was made, and additional details.

To learn more about CloudTrail, see the https://docs.aws.amazon.com/awscloudtrail/latest/userguide/[AWS CloudTrail User Guide].

[[service-name-info-in-cloudtrail,service-name-info-in-cloudtrail.title]]
== Amazon EKS information in CloudTrail

CloudTrail is enabled on your AWS account when you create the account. When activity occurs in Amazon EKS, that activity is recorded in a CloudTrail event along with other AWS service events in  **Event history**. You can view, search, and download recent events in your AWS account. For more information, see  https://docs.aws.amazon.com/awscloudtrail/latest/userguide/view-cloudtrail-events.html[Viewing Events with CloudTrail Event History].

For an ongoing record of events in your AWS account, including events for Amazon EKS, create a trail. A _trail_ enables CloudTrail to deliver log files to an Amazon S3 bucket. By default, when you create a trail in the console, the trail applies to all AWS Regions. The trail logs events from all Regions in the AWS partition and delivers the log files to the Amazon S3 bucket that you specify. Additionally, you can configure other AWS services to further analyze and act upon the event data collected in CloudTrail logs. For more information, see the following:



* https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-create-and-update-a-trail.html[Overview for creating a trail]
* {https---docs-aws-amazon-com-awscloudtrail-latest-userguide-cloudtrail-aws-service-specific-topics-html-cloudtrail-aws-service-specific-topics-integrations}[CloudTrail supported services and integrations]
* {https---docs-aws-amazon-com-awscloudtrail-latest-userguide-getting-notifications-top-level-html}[Configuring Amazon SNS notifications for CloudTrail]
* https://docs.aws.amazon.com/awscloudtrail/latest/userguide/receive-cloudtrail-log-files-from-multiple-regions.html[Receiving CloudTrail log files from multiple Regions]
* https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-receive-logs-from-multiple-accounts.html[Receiving CloudTrail log files from multiple accounts]

All Amazon EKS actions are logged by CloudTrail and are documented in the  https://docs.aws.amazon.com/slug/latest/APIReference/[Amazon EKS API Reference]. For example, calls to the ``ACTION_1``, `ACTION_2` and `ACTION_3` actions generate entries in the CloudTrail log files.

Every event or log entry contains information about who generated the request. The identity information helps you determine the following:



* Whether the request was made with root or AWS Identity and Access Management (IAM) user credentials.
* Whether the request was made with temporary security credentials for a role or federated user.
* Whether the request was made by another AWS service.

For more information, see the  https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-user-identity.html[CloudTrail userIdentity element].

[[understanding-service-name-entries,understanding-service-name-entries.title]]
== Understanding Amazon EKS log file entries

A trail is a configuration that enables delivery of events as log files to an Amazon S3 bucket that you specify. CloudTrail log files contain one or more log entries. An event represents a single request from any source and includes information about the requested action, the date and time of the action, request parameters, and so on. CloudTrail log files aren't an ordered stack trace of the public API calls, so they don't appear in any specific order.  

The following example shows a CloudTrail log entry that demonstrates the  action.

[source,json]
----

----