//!!NODE_ROOT <section>
:https---d0-awsstatic-com-whitepapers-compliance-AWS-HIPAA-Compliance-Whitepaper-pdf: https://d0.awsstatic.com/whitepapers/compliance/AWS_HIPAA_Compliance_Whitepaper.pdf

[."topic"]
[[compliance-validation,compliance-validation.title]]
= Compliance validation for Amazon EKS
:info_doctype: section
:info_title: Compliance validation for Amazon EKS
:info_titleabbrev: Compliance validation
:info_abstract: Learn what AWS services are in scope of a specific compliance program.

[abstract]
--
Learn what AWS services are in scope of a specific compliance program.
--

Third-party auditors assess the security and compliance of Amazon EKS as part of multiple AWS compliance programs. These include SOC, PCI, FedRAMP, HIPAA, and others.

For a list of AWS services in scope of specific compliance programs, see http://aws.amazon.com/compliance/services-in-scope/[AWS Services in Scope by Compliance Program]. For general information, see http://aws.amazon.com/compliance/programs/[AWS Compliance Programs].

You can download third-party audit reports using AWS Artifact. For more information, see https://docs.aws.amazon.com/artifact/latest/ug/downloading-documents.html[Downloading Reports in AWS Artifact].

Your compliance responsibility when using Amazon EKS is determined by the sensitivity of your data, your company's compliance objectives, and applicable laws and regulations. AWS provides the following resources to help with compliance:



* http://aws.amazon.com/quickstart/?awsf.quickstart-homepage-filter=categories%23security-identity-compliance[Security and Compliance Quick Start Guides] – These deployment guides discuss architectural considerations and provide steps for deploying security- and compliance-focused baseline environments on AWS.
* {https---d0-awsstatic-com-whitepapers-compliance-AWS-HIPAA-Compliance-Whitepaper-pdf}[Architecting for HIPAA Security and Compliance Whitepaper] – This whitepaper describes how companies can use AWS to create HIPAA-compliant applications.
* http://aws.amazon.com/compliance/resources/[AWS Compliance Resources] – This collection of workbooks and guides might apply to your industry and location.
* https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config.html[Evaluating Resources with Rules] in the _AWS Config Developer Guide_ – AWS Config; assesses how well your resource configurations comply with internal practices, industry guidelines, and regulations.
* https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html[AWS Security Hub] – This AWS service provides a comprehensive view of your security state within AWS that helps you check your compliance with security industry standards and best practices.
