//!!NODE_ROOT <section>

[."topic"]
[[data-protection,data-protection.title]]
= Data protection in Amazon EKS
:info_doctype: section
:info_title: Data protection in Amazon EKS
:info_titleabbrev: Data protection
:info_abstract: Learn how the [.shared]`AWS` shared responsibility model applies to data protection in \
        Amazon EKS.

[abstract]
--
Learn how the [.shared]`AWS` shared responsibility model applies to data protection in Amazon EKS.
--

The [.shared]`AWS` http://aws.amazon.com/compliance/shared-responsibility-model/[shared responsibility model] applies to data protection in Amazon EKS. As described in this model, [.shared]`AWS` is responsible for protecting the global infrastructure that runs all of the [.shared]`AWS-Cloud`. You are responsible for maintaining control over your content that is hosted on this infrastructure. This content includes the security configuration and management tasks for the [.shared]`AWS-services` that you use. For more information about data privacy, see the http://aws.amazon.com/compliance/data-privacy-faq[Data Privacy FAQ].For information about data protection in Europe, see the http://aws.amazon.com/blogs/security/the-aws-shared-responsibility-model-and-gdpr[[.shared]`AWS` Shared Responsibility Model and GDPR] blog post on the __AWS Security Blog__.

For data protection purposes, we recommend that you protect [.shared]`AWS-account` credentials and set up individual users with [.shared]`IAMlong` ([.shared]`IAM`). That way each user is given only the permissions necessary to fulfill their job duties. We also recommend that you secure your data in the following ways:



* Use multi-factor authentication (MFA) with each account.
* Use SSL/TLS to communicate with [.shared]`AWS` resources. We recommend TLS 1.2 or later.
* Set up API and user activity logging with [.shared]`CTlong`.
* Use [.shared]`AWS` encryption solutions, along with all default security controls within [.shared]`AWS-services`.
* Use advanced managed security services such as [.shared]`MCElong`, which assists in discovering and securing sensitive data that is stored in [.shared]`S3`.
* If you require FIPS 140-2 validated cryptographic modules when accessing [.shared]`AWS` through a command line interface or an API, use a FIPS endpoint. For more information about the available FIPS endpoints, see http://aws.amazon.com/compliance/fips/[Federal Information Processing Standard (FIPS) 140-2].

We strongly recommend that you never put sensitive identifying information, such as your customers' account numbers, into free-form fields such as a  *Name* field. This includes when you work with Amazon EKS or other [.shared]`AWS-services` using the console, API, [.shared]`CLI`, or [.shared]`AWS` SDKs. Any data that you enter into Amazon EKS or other services might get picked up for inclusion in diagnostic logs. When you provide a URL to an external server, don't include credentials information in the URL to validate your request to that server.

[[encryption-rest,encryption-rest.title]]
== Encryption at rest

TBD

[[encryption-transit,encryption-transit.title]]
== Encryption in transit

TBD