//!!NODE_ROOT <section>

[."topic"]
[[disaster-recovery-resiliency,disaster-recovery-resiliency.title]]
= Resilience in Amazon EKS
:info_doctype: section
:info_title: Resilience in Amazon EKS
:info_titleabbrev: Resilience
:info_abstract: Learn how AWS architecture supports data redundancy, and learn about specific \
                Amazon EKS features for data resiliency.

[abstract]
--
Learn how AWS architecture supports data redundancy, and learn about specific Amazon EKS features for data resiliency.
--

The AWS global infrastructure is built around AWS Regions and Availability Zones. Regions provide multiple physically separated and isolated Availability Zones, which are connected through low-latency, high-throughput, and highly redundant networking. With Availability Zones, you can design and operate applications and databases that automatically fail over between zones without interruption. Availability Zones are more highly available, fault tolerant, and scalable than traditional single or multiple data center infrastructures.

For more information about AWS Regions and Availability Zones, see http://aws.amazon.com/about-aws/global-infrastructure/[AWS Global Infrastructure].