//!!NODE_ROOT <section>
:https---d0-awsstatic-com-whitepapers-Security-AWS-Security-Whitepaper-pdf: https://d0.awsstatic.com/whitepapers/Security/AWS_Security_Whitepaper.pdf

[."topic"]
[[infrastructure-security,infrastructure-security.title]]
= Infrastructure security in Amazon EKS
:info_doctype: section
:info_title: Infrastructure security in Amazon EKS
:info_titleabbrev: Infrastructure security
:info_abstract: Learn how Amazon EKS isolates service traffic.

[abstract]
--
Learn how Amazon EKS isolates service traffic.
--

As a managed service, Amazon EKS is protected by the AWS global network security procedures that are described in the  {https---d0-awsstatic-com-whitepapers-Security-AWS-Security-Whitepaper-pdf}[Amazon Web Services: Overview of Security Processes] whitepaper.

You use AWS published API calls to access Amazon EKS through the network. Clients must support Transport Layer Security (TLS) 1.0 or later. We recommend TLS 1.2 or later. Clients must also support cipher suites with perfect forward secrecy (PFS) such as Ephemeral Diffie-Hellman (DHE) or Elliptic Curve Ephemeral Diffie-Hellman (ECDHE). Most modern systems such as Java 7 and later support these modes.

Additionally, requests must be signed using an access key ID and a secret access key that is associated with an IAM principal. Or you can use the https://docs.aws.amazon.com/STS/latest/APIReference/Welcome.html[AWS Security Token Service] (AWS STS) to generate temporary security credentials to sign requests.