//!!NODE_ROOT <chapter>
:https---docs-aws-amazon-com-vpc-latest-userguide-vpce-interface-html-access-service-though-endpoint: https://docs.aws.amazon.com/vpc/latest/userguide/vpce-interface.html#access-service-though-endpoint
:https---docs-aws-amazon-com-vpc-latest-userguide-vpce-interface-html-create-interface-endpoint: https://docs.aws.amazon.com/vpc/latest/userguide/vpce-interface.html#create-interface-endpoint
:https---docs-aws-amazon-com-vpc-latest-userguide-vpce-interface-html-vpce-interface-limitations: https://docs.aws.amazon.com/vpc/latest/userguide/vpce-interface.html#vpce-interface-limitations
[."topic"]
[[vpc-interface-endpoints,vpc-interface-endpoints.title]]
= Amazon EKS and interface VPC endpoints (AWS PrivateLink)
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: Amazon EKS and interface VPC endpoints \
            (AWS PrivateLink)
:info_titleabbrev: VPC endpoints (AWS PrivateLink)
:info_abstract: You can use an interface VPC endpoint to create \
    a private connection between your VPC and Amazon EKS without requiring access over the \
    internet or through a NAT device, a VPN connection, or an AWS Direct Connect connection.

[abstract]
--
You can use an interface VPC endpoint to create a private connection between your VPC and Amazon EKS without requiring access over the internet or through a NAT device, a VPN connection, or an AWS Direct Connect connection.
--

You can establish a private connection between your VPC and Amazon EKS by creating an  __interface VPC endpoint__. Interface endpoints are powered by http://aws.amazon.com/privatelink[AWS PrivateLink], a technology that enables you to privately access Amazon EKS APIs without an internet gateway, NAT device, VPN connection, or AWS Direct Connect connection. Instances in your VPC don't need public IP addresses to communicate with Amazon EKS APIs. Traffic between your VPC and Amazon EKS does not leave the Amazon network. 

Each interface endpoint is represented by one or more https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html[Elastic Network Interfaces] in your subnets. 

For more information, see https://docs.aws.amazon.com/vpc/latest/userguide/vpce-interface.html[Interface VPC endpoints (AWS PrivateLink)] in the __Amazon VPC User Guide__. 

[[vpc-endpoint-considerations,vpc-endpoint-considerations.title]]
== Considerations for Amazon EKS VPC endpoints

Before you set up an interface VPC endpoint for Amazon EKS, ensure that you review  {https---docs-aws-amazon-com-vpc-latest-userguide-vpce-interface-html-vpce-interface-limitations}[Interface endpoint properties and limitations] in the __Amazon VPC User Guide__. 

Amazon EKS supports making calls to all of its API actions from your VPC. 

VPC endpoint policies are not supported for Amazon EKS. By default, full access to Amazon EKS is allowed through the endpoint. For more information, see https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-access.html[Controlling access to services with VPC endpoints] in the __Amazon VPC User Guide__.

[[vpc-endpoint-create,vpc-endpoint-create.title]]
== Creating an interface VPC endpoint for Amazon EKS

You can create a VPC endpoint for the Amazon EKS service using either the Amazon VPC console or the AWS Command Line Interface (AWS CLI). For more information, see  {https---docs-aws-amazon-com-vpc-latest-userguide-vpce-interface-html-create-interface-endpoint}[Creating an interface endpoint] in the __Amazon VPC User Guide__.

Create a VPC endpoint for Amazon EKS using the following service name: 



* com.amazonaws.[replaceable]``region``.<service-name> 

If you enable private DNS for the endpoint, you can make API requests to Amazon EKS using its default DNS name for the Region, for example,  ``<service-name>.us-east-1.amazonaws.com``. 

For more information, see {https---docs-aws-amazon-com-vpc-latest-userguide-vpce-interface-html-access-service-though-endpoint}[Accessing a service through an interface endpoint] in the __Amazon VPC User Guide__.

[[vpc-endpoint-policy,vpc-endpoint-policy.title]]
== Creating a VPC endpoint policy for Amazon EKS

You can attach an endpoint policy to your VPC endpoint that controls access to Amazon EKS. The policy specifies the following information:



* The principal that can perform actions.
* The actions that can be performed.
* The resources on which actions can be performed.

For more information, see  https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-access.html[Controlling access to services with VPC endpoints] in the __Amazon VPC User Guide__. 

.Example: VPC endpoint policy for Amazon EKS actions
The following is an example of an endpoint policy for Amazon EKS. When attached to an endpoint, this policy grants access to the listed Amazon EKS actions for all principals on all resources.

[source]
----
{
   "Statement":[
      {
         "Principal":"*",
         "Effect":"Allow",
         "Action":[
            "servicename:action-1",
            "servicename:action-2",
            "servicename:action-2"
         ],
         "Resource":"*"
      }
   ]
}
----