//!!NODE_ROOT <chapter>
:https---console-aws-amazon-com-support-home--case-create-issueType-service-limit-increase: https://console.aws.amazon.com/support/home#/case/create?issueType=service-limit-increase
[[load-balancer-limits,load-balancer-limits.title]]
= Quotas for Amazon EKS
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: Quotas for Amazon EKS
:info_titleabbrev: Quotas
:info_abstract: Learn about the quotas for Amazon EKS.

[abstract]
--
Learn about the quotas for Amazon EKS.
--

Your AWS account has default quotas, formerly referred to as limits, for each AWS service. Unless otherwise noted, each quota is Region-specific. You can request increases for some quotas, and other quotas cannot be increased.

To view the quotas for Amazon EKS, open the https://console.aws.amazon.com/servicequotas/home[Service Quotas console]. In the navigation pane, choose *AWS services* and select  **Amazon EKS**.

To request a quota increase, see https://docs.aws.amazon.com/servicequotas/latest/userguide/request-quota-increase.html[Requesting a Quota Increase] in the __Service Quotas User Guide__. If the quota is not yet available in Service Quotas, use the {https---console-aws-amazon-com-support-home--case-create-issueType-service-limit-increase}[limit increase form].

Your AWS account has the following quotas related to Amazon EKS.

[[quotas-table]]
[cols="1,1", options="header"]
|===
| Resource
| Default


|Quota
|Description

|Quota
|Description
|===