//!!NODE_ROOT <chapter>
[."topic"]
[[security,security.title]]
= Security in Amazon EKS
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: Security in Amazon EKS
:info_titleabbrev: Security
:info_abstract: Configure Amazon EKS to meet your security and compliance objectives, and learn how to \
        use other AWS services that help you to secure your Amazon EKS resources.

[abstract]
--
Configure Amazon EKS to meet your security and compliance objectives, and learn how to use other AWS services that help you to secure your Amazon EKS resources.
--

Cloud security at AWS is the highest priority. As an AWS customer, you benefit from a data center and network architecture that is built to meet the requirements of the most security-sensitive organizations.

Security is a shared responsibility between AWS and you. The http://aws.amazon.com/compliance/shared-responsibility-model/[shared responsibility model] describes this as security of the cloud and security in the cloud:



* *Security of the cloud* – AWS is responsible for protecting the infrastructure that runs AWS services in the AWS Cloud. AWS also provides you with services that you can use securely. Third-party auditors regularly test and verify the effectiveness of our security as part of the http://aws.amazon.com/compliance/programs/[AWS Compliance Programs]. To learn about the compliance programs that apply to Amazon EKS, see http://aws.amazon.com/compliance/services-in-scope/[AWS Services in Scope by Compliance Program].
* *Security in the cloud* – Your responsibility is determined by the AWS service that you use. You are also responsible for other factors including the sensitivity of your data, your company`'s requirements, and applicable laws and regulations 

This documentation helps you understand how to apply the shared responsibility model when using Amazon EKS. It shows you how to configure Amazon EKS to meet your security and compliance objectives. You also learn how to use other AWS services that help you to monitor and secure your Amazon EKS resources.

[.topiclist-abbrev]
Contents

include::data-protection.adoc[leveloffset=+1]


include::security-iam.adoc[leveloffset=+1] Commenting out until can fix syntax issue


include::compliance-validation.adoc[leveloffset=+1]


include::disaster-recovery-resiliency.adoc[leveloffset=+1]


include::network-isolation.adoc[leveloffset=+1]
