//!!NODE_ROOT <chapter>
:https---docs-aws-amazon-com-IAM-latest-UserGuide-access-policies-examples-html: https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_examples.html
:https---docs-aws-amazon-com-IAM-latest-UserGuide-id-tags-html: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html
:https---docs-aws-amazon-com-IAM-latest-UserGuide-tutorial-billing-html: https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_billing.html
:https---docs-aws-amazon-com-general-latest-gr-aws-tasks-that-require-root-html: https://docs.aws.amazon.com/general/latest/gr/aws_tasks-that-require-root.html
[."topic"]
[[setting-up,setting-up.title]]
= Setting up Amazon EKS
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: Setting up Amazon EKS
:info_abstract: Insert chapter abstract text here.

[abstract]
--
Insert chapter abstract text here. 
--

Insert your introductory paragraph here.

[.topiclist]
[[Topic List]]

[[setting-up-aws-sign-up,setting-up-aws-sign-up.title]]
== Sign up for AWS

If you do not have an AWS account, complete the following steps to create one.

. Open https://portal.aws.amazon.com/billing/signup.
. Follow the online instructions.
+

Part of the sign-up procedure involves receiving a phone call and entering a verification code on the phone keypad.


[[setting-up-create-iam-user,setting-up-create-iam-user.title]]
== Create an IAM user
. Sign in to the https://console.aws.amazon.com/iam/[IAM console] as the account owner by choosing *Root user* and entering your AWS account email address. On the next page, enter your password.
+
NOTE: We strongly recommend that you adhere to the best practice of using the `Administrator` IAM user below and securely lock away the root user credentials. Sign in as the root user only to perform a few {https---docs-aws-amazon-com-general-latest-gr-aws-tasks-that-require-root-html}[account and service management tasks].
. In the navigation pane, choose *Users* and then choose  **Add user**.
. For **User name**, enter  ``Administrator``.
. Select the check box next to **AWS Management Console access**. Then select  **Custom password**, and then enter your new password in the text box.
. (Optional) By default, AWS requires the new user to create a new password when first signing in. You can clear the check box next to *User must create a new password at next sign-in* to allow the new user to reset their password after they sign in.
. Choose **Next: Permissions**.
. Under **Set permissions**, choose  **Add user to group**.
. Choose **Create group**.
. In the *Create group* dialog box, for  *Group name* enter  ``Administrators``.
. Choose **Filter policies**, and then select  *AWS managed -job function* to filter the table contents.
. In the policy list, select the check box for **AdministratorAccess**. Then choose  **Create group**.
+
NOTE: You must activate IAM user and role access to Billing before you can use the `AdministratorAccess` permissions to access the AWS Billing and Cost Management console. To do this, follow the instructions in {https---docs-aws-amazon-com-IAM-latest-UserGuide-tutorial-billing-html}[step 1 of the tutorial about delegating access to the billing console].
. Back in the list of groups, select the check box for your new group. Choose *Refresh* if necessary to see the group in the list.
. Choose **Next: Tags**.
. (Optional) Add metadata to the user by attaching tags as key-value pairs. For more information about using tags in IAM, see {https---docs-aws-amazon-com-IAM-latest-UserGuide-id-tags-html}[Tagging IAM Entities] in the __IAM User Guide__.
. Choose *Next: Review* to see the list of group memberships to be added to the new user. When you are ready to proceed, choose  **Create user**.

You can use this same process to create more groups and users and to give your users access to your AWS account resources. To learn about using policies that restrict user permissions to specific AWS resources, see  https://docs.aws.amazon.com/IAM/latest/UserGuide/access.html[Access Management] and {https---docs-aws-amazon-com-IAM-latest-UserGuide-access-policies-examples-html}[Example Policies].