[.topic]
[[hybrid-nodes-host-creds,hybrid-nodes-host-creds.title]]
= Host credentials through network disconnections
:info_doctype: section
:info_title: Host credentials through network disconnections
:info_titleabbrev: Host credentials
:info_abstract: Host credentials through network disconnections

EKS Hybrid Nodes is integrated with AWS Systems Manager (SSM) hybrid activations and AWS IAM Roles Anywhere for temporary IAM credentials that are used to authenticate the node with the EKS control plane. Both SSM and IAM Roles Anywhere have mechanisms for automatically refreshing the temporary credentials that it manages on the on-premises hosts. It is recommended to have a consistent credential provider across the hybrid nodes for your cluster, meaning use either SSM hybrid activations or IAM Roles Anywhere, but not both.

== SSM hybrid activations

The temporary credentials provisioned by SSM are valid for 1 hour. You cannot alter the credential validity duration when using SSM as your credential provider. The temporary credentials are automatically rotated by SSM before they expire and the rotation does not impact the status of your nodes or applications. However, when there are network disconnections between the SSM agent and the SSM regional endpoint, SSM is unable to refresh the credentials, and the credentials may expire. 

SSM uses an exponential backoff for credential refresh retry when it is unable to connect to the SSM regional endpoints. In SSM agent version `3.3.808.0` and later (released August 2024), the exponential backoff is capped at 30 minutes. Depending on the duration of your network disconnection, it may take up to 30 minutes for the SSM credentials to be refreshed, and hybrid nodes will not automatically reconnect to the EKS control plane until the credentials are refreshed. In this scenario, you can restart the SSM agent to force a credential refresh. A side effect of the current SSM credential refresh behavior is that nodes may reconnect at staggering times based on when the SSM agent running on the node is able to refresh its credentials. Because of this, you may see pod failover from nodes that are not yet reconnected to nodes that are already reconnected.

Get SSM agent version. You can alternatively check the Fleet Manager section of the SSM console.

[source,bash,subs="verbatim,attributes,quotes"]
----
# AL2023, RHEL
yum info amazon-ssm-agent

# Ubuntu
snap list amazon-ssm-agent
----

Restart SSM agent

[source,bash,subs="verbatim,attributes,quotes"]
----
# AL2023, RHEL 
systemctl restart amazon-ssm-agent

# Ubuntu
systemctl restart snap.amazon-ssm-agent.amazon-ssm-agent
----

View SSM agent logs

[source,bash,subs="verbatim,attributes,quotes"]
----
tail -f /var/log/amazon/ssm/amazon-ssm-agent.log
----

Expected log messages during network disconnections

[source,bash,subs="verbatim,attributes,quotes"]
----
INFO [CredentialRefresher] Credentials ready
INFO [CredentialRefresher] Next credential rotation will be in 29.995040663666668 minutes
ERROR [CredentialRefresher] Retrieve credentials produced error: RequestError: send request failed
INFO [CredentialRefresher] Sleeping for 35s before retrying retrieve credentials
ERROR [CredentialRefresher] Retrieve credentials produced error: RequestError: send request failed
INFO [CredentialRefresher] Sleeping for 56s before retrying retrieve credentials
ERROR [CredentialRefresher] Retrieve credentials produced error: RequestError: send request failed
INFO [CredentialRefresher] Sleeping for 1m24s before retrying retrieve credentials
----

== IAM Roles Anywhere

The temporary credentials provisioned by IAM Roles Anywhere are valid for 1 hour by default. You can configure the credential validity duration with IAM Roles Anywhere through the https://docs.aws.amazon.com/rolesanywhere/latest/userguide/authentication-create-session.html#credentials-object[`durationSeconds`] field of your IAM Roles Anywhere profile. The maximum credential validity duration is 12 hours. The https://docs.aws.amazon.com/managedservices/latest/ctref/management-advanced-identity-and-access-management-iam-update-maxsessionduration.html[`MaxSessionDuration`] setting on your Hybrid Nodes IAM role must be greater than the `durationSeconds` setting on your IAM Roles Anywhere profile.

When using IAM Roles Anywhere as the credential provider for your hybrid nodes, the reconnection to the EKS control plane after network disconnections generally occurs within seconds of the network restoration because the kubelet calls `aws_signing_helper credential-process` to get credentials on-demand. While not directly related to hybrid nodes and network disconnections, you can configure notifications and alerts for certificate expiry when you use IAM Roles Anywhere, see https://docs.aws.amazon.com/rolesanywhere/latest/userguide/customize-notification-settings.html[Customize notification settings in IAM Roles Anywhere].

