//!!NODE_ROOT <section>
[."topic"]
[[auditing-and-logging,auditing-and-logging.title]]
= Auditing and logging
:info_doctype: section
:info_title: Auditing and logging
:info_abstract: Auditing and logging
:info_titleabbrev: Auditing and logging
:imagesdir: images/

Collecting and analyzing [audit] logs is useful for a variety of
different reasons. Logs can help with root cause analysis and
attribution, i.e. ascribing a change to a particular user. When enough
logs have been collected, they can be used to detect anomalous behaviors
too. On EKS, the audit logs are sent to Amazon Cloudwatch Logs. The
audit policy for EKS is as follows:

[source,yaml]
----
apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  # Log aws-auth configmap changes
  - level: RequestResponse
    namespaces: ["kube-system"]
    verbs: ["update", "patch", "delete"]
    resources:
      - group: "" # core
        resources: ["configmaps"]
        resourceNames: ["aws-auth"]
    omitStages:
      - "RequestReceived"
  - level: None
    users: ["system:kube-proxy"]
    verbs: ["watch"]
    resources:
      - group: "" # core
        resources: ["endpoints", "services", "services/status"]
  - level: None
    users: ["kubelet"] # legacy kubelet identity
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["nodes", "nodes/status"]
  - level: None
    userGroups: ["system:nodes"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["nodes", "nodes/status"]
  - level: None
    users:
      - system:kube-controller-manager
      - system:kube-scheduler
      - system:serviceaccount:kube-system:endpoint-controller
    verbs: ["get", "update"]
    namespaces: ["kube-system"]
    resources:
      - group: "" # core
        resources: ["endpoints"]
  - level: None
    users: ["system:apiserver"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["namespaces", "namespaces/status", "namespaces/finalize"]
  - level: None
    users:
      - system:kube-controller-manager
    verbs: ["get", "list"]
    resources:
      - group: "metrics.k8s.io"
  - level: None
    nonResourceURLs:
      - /healthz*
      - /version
      - /swagger*
  - level: None
    resources:
      - group: "" # core
        resources: ["events"]
  - level: Request
    users: ["kubelet", "system:node-problem-detector", "system:serviceaccount:kube-system:node-problem-detector"]
    verbs: ["update","patch"]
    resources:
      - group: "" # core
        resources: ["nodes/status", "pods/status"]
    omitStages:
      - "RequestReceived"
  - level: Request
    userGroups: ["system:nodes"]
    verbs: ["update","patch"]
    resources:
      - group: "" # core
        resources: ["nodes/status", "pods/status"]
    omitStages:
      - "RequestReceived"
  - level: Request
    users: ["system:serviceaccount:kube-system:namespace-controller"]
    verbs: ["deletecollection"]
    omitStages:
      - "RequestReceived"
  # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
  # so only log at the Metadata level.
  - level: Metadata
    resources:
      - group: "" # core
        resources: ["secrets", "configmaps"]
      - group: authentication.k8s.io
        resources: ["tokenreviews"]
    omitStages:
      - "RequestReceived"
  - level: Request
    resources:
      - group: ""
        resources: ["serviceaccounts/token"]
  - level: Request
    verbs: ["get", "list", "watch"]
    resources: 
      - group: "" # core
      - group: "admissionregistration.k8s.io"
      - group: "apiextensions.k8s.io"
      - group: "apiregistration.k8s.io"
      - group: "apps"
      - group: "authentication.k8s.io"
      - group: "authorization.k8s.io"
      - group: "autoscaling"
      - group: "batch"
      - group: "certificates.k8s.io"
      - group: "extensions"
      - group: "metrics.k8s.io"
      - group: "networking.k8s.io"
      - group: "policy"
      - group: "rbac.authorization.k8s.io"
      - group: "scheduling.k8s.io"
      - group: "settings.k8s.io"
      - group: "storage.k8s.io"
    omitStages:
      - "RequestReceived"
  # Default level for known APIs
  - level: RequestResponse
    resources: 
      - group: "" # core
      - group: "admissionregistration.k8s.io"
      - group: "apiextensions.k8s.io"
      - group: "apiregistration.k8s.io"
      - group: "apps"
      - group: "authentication.k8s.io"
      - group: "authorization.k8s.io"
      - group: "autoscaling"
      - group: "batch"
      - group: "certificates.k8s.io"
      - group: "extensions"
      - group: "metrics.k8s.io"
      - group: "networking.k8s.io"
      - group: "policy"
      - group: "rbac.authorization.k8s.io"
      - group: "scheduling.k8s.io"
      - group: "settings.k8s.io"
      - group: "storage.k8s.io"
    omitStages:
      - "RequestReceived"
  # Default level for all other requests.
  - level: Metadata
    omitStages:
      - "RequestReceived"
----

== Recommendations

=== Enable audit logs

The audit logs are part of the EKS managed Kubernetes control plane logs
that are managed by EKS. Instructions for enabling/disabling the control
plane logs, which includes the logs for the Kubernetes API server, the
controller manager, and the scheduler, along with the audit log, can be
found here,
https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html#enabling-control-plane-log-export.

!!! info When you enable control plane logging, you will incur
https://aws.amazon.com/cloudwatch/pricing/[costs] for storing the logs
in CloudWatch. This raises a broader issue about the ongoing cost of
security. Ultimately you will have to weigh those costs against the cost
of a security breach, e.g. financial loss, damage to your reputation,
etc. You may find that you can adequately secure your environment by
implementing only some of the recommendations in this guide.

!!! warning The maximum size for a CloudWatch Logs entry is
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html[256KB]
whereas the maximum Kubernetes API request size is 1.5MiB. Log entries
greater than 256KB will either be truncated or only include the request
metadata.

=== Utilize audit metadata

Kubernetes audit logs include two annotations that indicate whether or
not a request was authorized `+authorization.k8s.io/decision+` and the
reason for the decision `+authorization.k8s.io/reason+`. Use these
attributes to ascertain why a particular API call was allowed.

=== Create alarms for suspicious events

Create an alarm to automatically alert you where there is an increase in
403 Forbidden and 401 Unauthorized responses, and then use attributes
like `+host+`, `+sourceIPs+`, and `+k8s_user.username+` to find out
where those requests are coming from.

=== Analyze logs with Log Insights

Use CloudWatch Log Insights to monitor changes to RBAC objects,
e.g. Roles, RoleBindings, ClusterRoles, and ClusterRoleBindings. A few
sample queries appear below:

Lists updates to the `+aws-auth+` ConfigMap:

[source,bash]
----
fields @timestamp, @message
| filter @logStream like "kube-apiserver-audit"
| filter verb in ["update", "patch"]
| filter objectRef.resource = "configmaps" and objectRef.name = "aws-auth" and objectRef.namespace = "kube-system"
| sort @timestamp desc
----

Lists creation of new or changes to validation webhooks:

[source,bash]
----
fields @timestamp, @message
| filter @logStream like "kube-apiserver-audit"
| filter verb in ["create", "update", "patch"] and responseStatus.code = 201
| filter objectRef.resource = "validatingwebhookconfigurations"
| sort @timestamp desc
----

Lists create, update, delete operations to Roles:

[source,bash]
----
fields @timestamp, @message
| sort @timestamp desc
| limit 100
| filter objectRef.resource="roles" and verb in ["create", "update", "patch", "delete"]
----

Lists create, update, delete operations to RoleBindings:

[source,bash]
----
fields @timestamp, @message
| sort @timestamp desc
| limit 100
| filter objectRef.resource="rolebindings" and verb in ["create", "update", "patch", "delete"]
----

Lists create, update, delete operations to ClusterRoles:

[source,bash]
----
fields @timestamp, @message
| sort @timestamp desc
| limit 100
| filter objectRef.resource="clusterroles" and verb in ["create", "update", "patch", "delete"]
----

Lists create, update, delete operations to ClusterRoleBindings:

[source,bash]
----
fields @timestamp, @message
| sort @timestamp desc
| limit 100
| filter objectRef.resource="clusterrolebindings" and verb in ["create", "update", "patch", "delete"]
----

Plots unauthorized read operations against Secrets:

[source,bash]
----
fields @timestamp, @message
| sort @timestamp desc
| limit 100
| filter objectRef.resource="secrets" and verb in ["get", "watch", "list"] and responseStatus.code="401"
| stats count() by bin(1m)
----

List of failed anonymous requests:

[source,bash]
----
fields @timestamp, @message, sourceIPs.0
| sort @timestamp desc
| limit 100
| filter user.username="system:anonymous" and responseStatus.code in ["401", "403"]
----

=== Audit your CloudTrail logs

AWS APIs called by pods that are utilizing IAM Roles for Service
Accounts (IRSA) are automatically logged to CloudTrail along with the
name of the service account. If the name of a service account that
wasn’t explicitly authorized to call an API appears in the log, it may
be an indication that the IAM role’s trust policy was misconfigured.
Generally speaking, Cloudtrail is a great way to ascribe AWS API calls
to specific IAM principals.

=== Use CloudTrail Insights to unearth suspicious activity

CloudTrail insights automatically analyzes write management events from
CloudTrail trails and alerts you of unusual activity. This can help you
identify when there’s an increase in call volume on write APIs in your
AWS account, including from pods that use IRSA to assume an IAM role.
See
https://aws.amazon.com/blogs/aws/announcing-cloudtrail-insights-identify-and-respond-to-unusual-api-activity/[Announcing
CloudTrail Insights: Identify and Response to Unusual API Activity] for
further information.

=== Additional resources

As the volume of logs increases, parsing and filtering them with Log
Insights or another log analysis tool may become ineffective. As an
alternative, you might want to consider running
https://github.com/falcosecurity/falco[Sysdig Falco] and
https://github.com/sysdiglabs/ekscloudwatch[ekscloudwatch]. Falco
analyzes audit logs and flags anomalies or abuse over an extended period
of time. The ekscloudwatch project forwards audit log events from
CloudWatch to Falco for analysis. Falco provides a set of
https://github.com/falcosecurity/plugins/blob/master/plugins/k8saudit/rules/k8s_audit_rules.yaml[default
audit rules] along with the ability to add your own.

Yet another option might be to store the audit logs in S3 and use the
SageMaker
https://docs.aws.amazon.com/sagemaker/latest/dg/randomcutforest.html[Random
Cut Forest] algorithm to anomalous behaviors that warrant further
investigation.

== Tools and resources

The following commercial and open source projects can be used to assess
your cluster’s alignment with established best practices:

* https://catalog.workshops.aws/eks-security-immersionday/en-US/5-detective-controls[Amazon
EKS Security Immersion Workshop - Detective Controls]
* https://github.com/Shopify/kubeaudit[kubeaudit]
* https://github.com/octarinesec/kube-scan[kube-scan] Assigns a risk
score to the workloads running in your cluster in accordance with the
Kubernetes Common Configuration Scoring System framework
* https://kubesec.io/[kubesec.io]
* https://github.com/FairwindsOps/polaris[polaris]
* https://github.com/aquasecurity/starboard[Starboard]
* https://support.snyk.io/hc/en-us/articles/360003916138-Kubernetes-integration-overview[Snyk]
* https://github.com/kubescape/kubescape[Kubescape] Kubescape is an open
source kubernetes security tool that scans clusters, YAML files, and
Helm charts. It detects misconfigurations according to multiple
frameworks (including
https://www.armosec.io/blog/kubernetes-hardening-guidance-summary-by-armo/?utm_source=github&utm_medium=repository[NSA-CISA]
and
https://www.microsoft.com/security/blog/2021/03/23/secure-containerized-environments-with-updated-threat-matrix-for-kubernetes/[MITRE
ATT&CK®].)
